# Generated by Django 5.0.7 on 2024-07-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_category_options_remove_post_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='amazon_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
