# Generated by Django 5.0.7 on 2024-07-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
